-- MySQL Script generated by MySQL Workbench
-- Sat Feb  6 13:07:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mantenimiento_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mantenimiento_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mantenimiento_bd` DEFAULT CHARACTER SET utf8 ;
USE `mantenimiento_bd` ;

-- -----------------------------------------------------
-- Table `mantenimiento_bd`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mantenimiento_bd`.`Cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_cliente` VARCHAR(45) NOT NULL,
  `apellido_paterno` VARCHAR(45) NOT NULL,
  `apellido_materno` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  `colonia` VARCHAR(45) NULL,
  `codigo_postal` INT NULL,
  `telefono_fijo` CHAR(10) NULL,
  `telefono_celular` CHAR(10) NOT NULL,
  `correo_electronico` VARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento_bd`.`OrdenServicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mantenimiento_bd`.`OrdenServicio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `diagnostico_rapido` VARCHAR(300) NOT NULL,
  `costo_estimado` FLOAT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ReporteDiagnostico_Cliente1_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_ReporteDiagnostico_Cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `mantenimiento_bd`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento_bd`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mantenimiento_bd`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento_bd`.`SeguimientoOrden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mantenimiento_bd`.`SeguimientoOrden` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_asignacion` DATE NULL,
  `fecha_entrega` DATE NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `users_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_SeguimientoOrden_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_SeguimientoOrden_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mantenimiento_bd`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento_bd`.`TipoDispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mantenimiento_bd`.`TipoDispositivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_dispositivo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(250) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento_bd`.`EstadoDispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mantenimiento_bd`.`EstadoDispositivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `enciende` INT NULL,
  `colores_correctos` INT NULL,
  `botones_completos` TINYINT NOT NULL,
  `golpeado` TINYINT NOT NULL,
  `condiciones_fisicas` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `sistema_operativo` VARCHAR(45) NULL,
  `contrasenia` VARCHAR(250) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento_bd`.`Software`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mantenimiento_bd`.`Software` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_software` VARCHAR(250) NULL,
  `licencia` TINYINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento_bd`.`Dispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mantenimiento_bd`.`Dispositivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numSerie` VARCHAR(250) NOT NULL,
  `nombre_dispositivo` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `tipoDispositivo_id` INT NOT NULL,
  `estadoDispositivo_id` INT NOT NULL,
  `software_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Dispositivo_TipoDispositivo1_idx` (`tipoDispositivo_id` ASC) VISIBLE,
  INDEX `fk_Dispositivo_EstadoDispositivo1_idx` (`estadoDispositivo_id` ASC) VISIBLE,
  INDEX `fk_Dispositivo_Software1_idx` (`software_id` ASC) VISIBLE,
  UNIQUE INDEX `numSerie_UNIQUE` (`numSerie` ASC) VISIBLE,
  CONSTRAINT `fk_Dispositivo_TipoDispositivo1`
    FOREIGN KEY (`tipoDispositivo_id`)
    REFERENCES `mantenimiento_bd`.`TipoDispositivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dispositivo_EstadoDispositivo1`
    FOREIGN KEY (`estadoDispositivo_id`)
    REFERENCES `mantenimiento_bd`.`EstadoDispositivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dispositivo_Software1`
    FOREIGN KEY (`software_id`)
    REFERENCES `mantenimiento_bd`.`Software` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento_bd`.`Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mantenimiento_bd`.`Servicio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `ordenServicio_id` INT NOT NULL,
  `ordenSeguimiento_id` INT NOT NULL,
  `dispositivo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Dispositivo_OrdenServicio1_idx` (`ordenServicio_id` ASC) VISIBLE,
  INDEX `fk_Dispositivo_SeguimientoOrden1_idx` (`ordenSeguimiento_id` ASC) VISIBLE,
  INDEX `fk_Servicio_Dispositivo1_idx` (`dispositivo_id` ASC) VISIBLE,
  CONSTRAINT `fk_Dispositivo_OrdenServicio1`
    FOREIGN KEY (`ordenServicio_id`)
    REFERENCES `mantenimiento_bd`.`OrdenServicio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dispositivo_SeguimientoOrden1`
    FOREIGN KEY (`ordenSeguimiento_id`)
    REFERENCES `mantenimiento_bd`.`SeguimientoOrden` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servicio_Dispositivo1`
    FOREIGN KEY (`dispositivo_id`)
    REFERENCES `mantenimiento_bd`.`Dispositivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento_bd`.`MantPrev`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mantenimiento_bd`.`MantPrev` (
  `idMantPrev` INT NOT NULL AUTO_INCREMENT,
  `actividad` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(250) NOT NULL,
  `insumos_utilizados` VARCHAR(250) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`idMantPrev`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento_bd`.`MantCorrect`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mantenimiento_bd`.`MantCorrect` (
  `idMantCorrect` INT NOT NULL AUTO_INCREMENT,
  `hardware_actual` VARCHAR(45) NOT NULL,
  `software_actual` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`idMantCorrect`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento_bd`.`Mantenimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mantenimiento_bd`.`Mantenimiento` (
  `costo_final` DOUBLE NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `mantPrev_idMantPrevent` INT NOT NULL,
  `mantCorrect_idMantCorrect` INT NOT NULL,
  `servicio_id` INT NOT NULL,
  INDEX `fk_Mantenimiento_Preventivo_Hardware_has_Mantenimiento_Prev_idx1` (`mantPrev_idMantPrevent` ASC) VISIBLE,
  INDEX `fk_Mantenimiento_Mantenimiento_Correctivo1_idx` (`mantCorrect_idMantCorrect` ASC) VISIBLE,
  INDEX `fk_Mantenimiento_Dispositivo1_idx` (`servicio_id` ASC) VISIBLE,
  CONSTRAINT `fk_Mantenimiento_Preventivo_Hardware_has_Mantenimiento_Preven1`
    FOREIGN KEY (`mantPrev_idMantPrevent`)
    REFERENCES `mantenimiento_bd`.`MantPrev` (`idMantPrev`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mantenimiento_Mantenimiento_Correctivo1`
    FOREIGN KEY (`mantCorrect_idMantCorrect`)
    REFERENCES `mantenimiento_bd`.`MantCorrect` (`idMantCorrect`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mantenimiento_Dispositivo1`
    FOREIGN KEY (`servicio_id`)
    REFERENCES `mantenimiento_bd`.`Servicio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento_bd`.`Refacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mantenimiento_bd`.`Refacciones` (
  `numSerie` VARCHAR(250) NOT NULL,
  `nombre_refaccion` VARCHAR(250) NOT NULL,
  `descripcion` VARCHAR(250) NOT NULL,
  `costo` FLOAT NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`numSerie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento_bd`.`Mant_Correct_has_Refacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mantenimiento_bd`.`Mant_Correct_has_Refacciones` (
  `mantCorrect_idMantCorrect` INT NOT NULL,
  `refacciones_numSerie` VARCHAR(250) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  INDEX `fk_Mantenimiento_Correctivo_has_Refacciones_Mantenimiento_C_idx` (`mantCorrect_idMantCorrect` ASC) VISIBLE,
  INDEX `fk_Mant_Correct_has_Refacciones_Refacciones1_idx` (`refacciones_numSerie` ASC) VISIBLE,
  CONSTRAINT `fk_Mantenimiento_Correctivo_has_Refacciones_Mantenimiento_Cor1`
    FOREIGN KEY (`mantCorrect_idMantCorrect`)
    REFERENCES `mantenimiento_bd`.`MantCorrect` (`idMantCorrect`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mant_Correct_has_Refacciones_Refacciones1`
    FOREIGN KEY (`refacciones_numSerie`)
    REFERENCES `mantenimiento_bd`.`Refacciones` (`numSerie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
